### ISSUE TITLE
Segfault when processing many node

### ISSUE THREAD

**Issue by sebastic** [osmcode/pyosmium#105]
The following minimal test case crashes with a segfault when processing [nodes.osm](https://linuxminded.nl/tmp/nodes.osm)
```python
#!/usr/bin/python3

import os
import pprint

import osmium


class DataHandler(osmium.SimpleHandler):
    nodes = []

    def __init__(self):
        osmium.SimpleHandler.__init__(self)

    def node(self, n):
        print("Adding node: %s" % pprint.pformat(n))

        self.nodes.append(n)


if __name__ == "__main__":
    os.environ['PYTHONUNBUFFERED'] = '1'

    file = '/tmp/nodes.osm'

    dh = DataHandler()
    dh.apply_file(file)

    if len(dh.nodes) > 0:
        print("Processing nodes")

        for n in dh.nodes:
             print("n: %s" % pprint.pformat(n))
```

When not using pprint, but processing the tags the code hangs.

This happens on both Debian stretch & unstable:
```
$ lsb_release -sd
Debian GNU/Linux 9.8 (stretch)
$ python3 --version
Python 3.5.3
$ dpkg -l python3-pyosmium | grep ^ii
ii  python3-pyosmium 2.15.1-1~bpo9+1 amd64        Osmium library bindings for Python 3
```
```
$ lsb_release -sd
Debian GNU/Linux buster/sid
$ python3 --version
Python 3.7.3
$ dpkg -l python3-pyosmium | grep ^ii
ii  python3-pyosmium 2.15.2-1~exp1 amd64        Osmium library bindings for Python 3
```

**Comment by joto** [comment]
`self.nodes.append(n)` is the culprit here. This keeps references to objects that will be gone once you leave the handler. You are supposed to work on the objects in the handler function only.

**Comment by sebastic** [comment]
Would it be possible to make the objects compatible with pickle to allow using `copy.deepcopy()`?

I don't see how I can extract all the objects from the OSM data and then process them if this all has to happen in the handler.

In the full code (a Python implementation of a pgsnapshot importer) I extract the uid/user mapping from the nodes/ways/relations and then the process the objects object types.

Is the design of osmium meant to use `apply_file` with different handlers for each of the different processing actions that needs to happen on the OSM data?

**Comment by sebastic** [comment]
Changing the `node` callback to create a dict seems to suffice:
```python
    def node(self, n):
        tags = {}
        if len(n.tags) > 0:
            for tag in n.tags:
                tags[tag.k] = tag.v

        _node = {
                  'id':        n.id,
                  'version':   n.version,
                  'uid':       n.uid,
                  'timestamp': n.timestamp,
                  'changeset': n.changeset,
                  'tags':      tags,
                  'lat':       n.location.lat,
                  'lon':       n.location.lon,
                }

        print("Adding node: %s" % pprint.pformat(_node))

        self.nodes.append(_node)
```

Making the objects copyable would provide greater flexibility though.

**Comment by joto** [comment]
The objects are kept in a special way (this is done inside the C++ libosmium side) to minimize memory overhead and speed up processing. Usually you don't need everything from an OSM object, but only some data, so it is a good compromise to do it this way, but it means you have to decide exactly which data you need and only copy that data and hold it in some intermediate structure.

You are encouraged to read the file several times with different handlers if you need that for processing. For small data extracts keeping everything in memory is possible, but as soon as you are using the whole planet or larger extracts, chances are there will not be enough memory.

I believe your code is still not correct, because `tags` is still dangling.

**Comment by sebastic** [comment]
Because the copy module cannot be used, how should objects and/or properties be copied instead?

Using a formatted string seems like a hack:
```python
tags["%s" % tag.k] = "%s" % tag.v
```

**Comment by joto** [comment]
Ups. I am sorry, I didn't read your code correctly. I think your original code to copy the tags should work.

**Comment by lonvia** [comment]
Yes, the tag list copy is fine like that. Although, because `tags` is a dict-like object, you can do it easier:

```
tags = dict(n.tags)
```

I could provide an implementation of `__deepcopy__` although I'm a bit reluctant to do so because it goes against the philosophy of pyosmium, which is intended for streaming processing of OSM data. If I understand your usecase right, you would write the OSM data itself in the handler in the database and in parallel save the uid/username mapping in a dict. In the end you'd only have to process the user dict outside the handler. No need to save any other data from the objects.

**Comment by sebastic** [comment]
Thanks for the feedback. With the segfault fixed, and deepcopy support not matching with the design philosophy, this issue can be considered resolved.

**Comment by tibbe** [comment]
> ...it means you have to decide exactly which data you need and only copy that data and hold it in some intermediate structure.

It's not exactly easy to figure out what needs to be manually copied or not. For example, can one hold on to a `osmium.osm.Location`? Is the principle that one cannot hold on to any class inside the `osmium.osm` module?

**Comment by lonvia** [comment]
Please have a look at the tests: https://github.com/osmcode/pyosmium/blob/master/test/test_dangling_references.py
