### ISSUE TITLE
Dictionary-like types should (implicitly?) convert to Python dicts

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/pyosmium#106]
Suppose I have a key-value `TagList` and I want to turn it into a proper Python dict.

At the moment I can not convert via `dict(tags)`:

```Python
   props = dict(n.tags)
TypeError: cannot convert dictionary update sequence element #0 to a sequence
```

the workaround is to be explicit

```Python
props = {tag.k: tag.v for tag in n.tags}
```

Looking at the implementation

https://github.com/osmcode/pyosmium/blob/f857b196aa201443e907684a85a9fdf205b26f5b/lib/osm.cc#L101-L127

I see no reason why pyosmium's custom dictionary-like objects should not convert to dicts. Am I missing something? The keys should be unique, no?

Happy Easter :rabbit: hacking!

**Comment by lonvia** [comment]
The iterator of `osmium.TagList` returns `osmiumTag`s. To make that work together with `dict()`, Tag needs to be convertible to a tuple `(k, v)`.

**Comment by lonvia** [comment]
Easy to do in python:

```
def __tag_iter(t):
    yield t.k
    yield t.v

Tag.__iter__ = __tag_iter
```

Now I only have to figure out what the equivalent code in pybind11 is.

**Comment by daniel-j-h** [comment]
I think I found an example how to do this; see the following (and above)

https://github.com/pybind/pybind11/blob/9bb3313162c0b856125e481ceece9d8faa567716/tests/test_sequences_and_iterators.cpp#L204-L237

**Comment by lonvia** [comment]
Reading the Python docs some more, the actual correct way to make the TagList a mapping object is to provide the `keys()` function. It is fairly easy to write a key iterator. The problem with it is that `dict(tags)` actually becomes very inefficient. `__getitem__` is not very fast because it needs to iterate over the list of tags to find the item. If Python goes over the keys and then uses `__getitem__` to get the value, then we have (num_tags + 1) iterations over the tag list.

**Comment by morandd** [comment]
In my testing this new
   d = dict(o.tags)
is twice as slow as the old
   d = {tag.k: tag.v for tag in o.tags}

I'm not sure how to fix or work around this :/ 
I left a comment about this on the relevant commit e54d320
