### ISSUE TITLE
Convert to GeoJSON

### ISSUE THREAD

**Issue by lhorus** [osmcode/pyosmium#108]
The examples folder contains an example of [converting](https://github.com/osmcode/pyosmium/blob/master/examples/convert.py) the file format, I would say that it allows conversion to traditional formats - .osm, .osm.pbf and so on. How does one apply the example to GeoJSON? I noticed that PyOsmium includes a GeoJSON factory.

**Comment by joto** [comment]
The `convert.py` example isn't a good starting point, because it only shows how to convert between file formats supported by Osmium itself. Use, for instance, the `osm_file_stats.py` example as a starting point and write your own handler that creates the GeoJSON from the data.

The GeoJSON factory is only used to generate the geometries from nodes, ways, and areas in GeoJSON format, you need some code around it to do the conversion of the tags etc. yourself.

Note that the  [osmium export](https://docs.osmcode.org/osmium/latest/osmium-export.html) command can convert OSM data to GeoJSON, maybe that's enough for your use case.
