### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by freundTech** [osmcode/pyosmium#132]
I'm trying to find nodes with specific tags and am running into a problem, where pyosmium uses up all my memory (16GB. 10+ GB taken by python), despite not keeping any data from the handler functions (only calling print from there)

For comparison I tried the amenity_list.py from the examples directory and ran into the same problem.

Could there maybe be a memory leak somewhere or is pyosmium supposed to use that much memory?

I'm using pyosmium 2.15.4 and am running the amenity_list.py script against planet-200323.osm.pbf

**Comment by lonvia** [comment]
If your program needs a lot of memory, then this is normally the node location cache. The location cache is needed only when handling geometries (when an area callback is given or the `locations` parameter is set in `apply_file()`). You need a lot of memory to cache locations for a planet-sized file, so normally it is better to switch to caching on disk. See [the documentation about location cache](https://docs.osmcode.org/pyosmium/master/intro.html#handling-geometries) for using a disk-backed dense cache.

NB: processing the full planet with pyosmium is going to take a very,very long time because python as a scripting language is not the fastest. It is always a good idea to pre-filter the data you need using filtering tools like [osmium-tool](https://osmcode.org/osmium-tool/).

**Comment by freundTech** [comment]
Thanks. Caching it on disk saved the problem. It's not using "only" 3GB of memory, which is still a lot, but something my computer can handle.

I currently don't care about performance, as I'm only prototyping, but thanks for the tip.
