### ISSUE TITLE
multiprocessing + .osm.pbf file = deadlock

### ISSUE THREAD

**Issue by ltog** [osmcode/pyosmium#137]
For a side project of mine ( https://gitlab.com/ltog/gwr-filter ) I did some experimenting using subprocesses to speed up the processing of OSM files by pyosmium. In general, this worked well. However, when trying to implement a two-pass read for evaluating [associatedStreet relations](https://wiki.openstreetmap.org/wiki/Relation:associatedStreet) , I have encountered some strange behaviour that looks like a bug in osmium/pyosmium to me.

Call the script below like this:

    python3 ./gwr-mini.py liechtenstein-latest.osm liechtenstein-latest.osm.pbf

(You can use the extracty provided by http://download.geofabrik.de/europe/liechtenstein.html but I guess any `.osm.pbf` will do...)

You will see that the script hangs at the line marked A. Interestingly, this is true if and only if both following conditions are met:

1. The second argument is of type `.osm.pbf`. (`.osm` files work fine)
2. The seemingly unrelated line B is active.

I tested with versions 3.0.0 and 2.15.4.

```python
#!/usr/bin/env python3

import osmium
import sys
from multiprocessing import Pool

class FirstOsmReader(osmium.SimpleHandler):
    def __init__(self):
        super(FirstOsmReader, self).__init__()
        print(f'Initializing {self.__class__}')
        self.count=0

    def relation(self, r):
        if self.count<4:
            print(f'FirstOsmReader.way(): r={r}')
            self.count += 1
        pass

    def work1(self, filename: str):
        self.apply_file(filename=filename, locations=False)
        return

class SecondOsmReader(osmium.SimpleHandler):
    def __init__(self, worker_id: int, num_workers: int):
        super(SecondOsmReader, self).__init__()
        print(f'Initializing {self.__class__}')
        self.num_workers = num_workers
        self.worker_id = worker_id
        self.count=0

    def node(self, n):
        if not n.id % self._num_workers == self._worker_id:
            return
        if self.count<4:
            print(f'SecondOsmReader.node(): n={n}')
            self.count += 1

    def work2(self, worker_id: int, num_workers: int, filename: str):
        self._worker_id = worker_id
        self._num_workers = num_workers
        print('work2: before apply')
        self.apply_file(filename=filename, locations=True) # A: this line hangs
        print('work2: after apply')
        return

def work(worker_id: int, num_workers: int, filename: str):
    second_osm_reader = SecondOsmReader(worker_id, num_workers)
    return second_osm_reader.work2(worker_id, num_workers, filename)

if __name__ == '__main__':
    num_workers = 2
    f1=sys.argv[1]
    f2=sys.argv[2]
    print(f'f1={f1}')
    print(f'f2={f2}')

    first_osm_reader = FirstOsmReader()
    first_osm_reader.work1(f1) # B: if this line is active, it triggers a hang in line A

    with Pool(processes=num_workers) as pool:
        w = num_workers
        myargs = zip([x for x in range(w)], [w]*w, [f2]*w)
        print(f'myargs={[x for x in range(w)], [w]*w, [f2]*w}')
        for result in pool.starmap(work, myargs):
            pass
```

**Comment by lonvia** [comment]
You cannot simply fork a libosmium application like that. libosmium holds a global thread pool that it uses when parsing the files. When you fork, only the main thread gets forked and the thread pool ends up in an invalid state. It has only worked until now because the thread pool happened to be still empty when you set up the Python Pool. And it works with an .osm file because xml parsing doesn't use the thread pool. Using the libosmium C++ API you could create a private thread pool per form and use that in your reader. pyosmium does not expose the interface for that, so that is not an option for you. You can use the Python Pool in [spawn mode](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods). This will reinitialise the libosmium library for each of your processes and all is well.

On a general note: I don't think your approach to multi-processing is the best one. Both your processes have to parse the complete file. You can only gain time with the actual processing in the callbacks. That sounds like you would be better off to start with the multiprocessing after the callback: in the osmium handler just copy the relevant data out of the OSMObject and push it into a queue. Then spawn workers that process this queue. Apart from solving the problem of forking libosmium, it also has the advantage that you only have one location cache. Your current solution would create a cache in each worker which can get very expensive very quickly.

General note 2: you really should look into prefiltering the data with osmium tool. This will speed up processing much more than any multiprocessing can do.
