### ISSUE TITLE
[improvement] Multithreading support ? 

### ISSUE THREAD

**Issue by Fkawala** [osmcode/pyosmium#18]
Hello, 

I wonder what would it take to enable multi-threaded reading for PBF files ?

From what I get from [source](http://docs.osmcode.org/libosmium/latest/reader_8hpp_source.html), the reader support multi-threading.    

If the modifications are straight forward I'm ready to do it, but my cpp skills are quite limited.

Bests,
F.

**Comment by joto** [comment]
PBF reading is multithreaded. Libosmium handles that automagically behind the scenes.

**Comment by Fkawala** [comment]
Automagically :) great ! Yet when I run the [osm_file_stats.py](https://github.com/osmcode/pyosmium/blob/master/examples/osm_file_stats.py), only one core works. What am I missing ?

**Comment by joto** [comment]
Libosmium decides how many threads to run based on how many cores you have. You can change this as described here: http://docs.osmcode.org/libosmium-manual/#run-time-configuration . But the problem is usually that your main thread (the one running your C++ or Python program) is the bottle neck, so putting more cores on parsing PBF won't help, because they are all waiting for the main thread to actually do something with the data. This is especially true for pyosmium, because the overhead of python means the main thread will be much much slower then the PBF parsing.

Theoretically the logic in the main thread could be handled in multiple threads, too. But this is much more complicated for the user of libosmium or pyosmium, because they would be exposed to the multithreading and have to handle locking or whatever to keep the threads out of each others hairs. And they have to keep in mind that data will be unordered. Currently the magic in libosmium will make sure you still get the data in the same order it is in the file. So, this mode of operation is not supported by libosmium out of the box. If you want to make the main thread multithreaded you can certainly do so, but then you are totally on your own.

**Comment by Fkawala** [comment]
Thanks for this detailed explanation. I'll save me an headache and won't attempt to parallelize the main python thread. Assuming I still want the PBF to read in parallel (which I understand is not quite useful), I wonder if : (a) the entities would be totally scrambled (eg. ways interleaved with nodes and relation) or (b) the entities would be read as they appear in the file and mixed-up locally (eg. as threads occurs).

**Comment by joto** [comment]
As I say above: "the magic in libosmium will make sure you still get the data in the same order it is in the file."

**Comment by Fkawala** [comment]
Sorry, I've misread your previous message.
