### ISSUE TITLE
Getting header info

### ISSUE THREAD

**Issue by batFINGER** [osmcode/pyosmium#19]
Hi,

Having trouble in determining how to get header info akin to https://github.com/osmcode/node-osmium/blob/master/doc/tutorial.md#getting-the-file-header using pyosmium.  

A small example to point me in the right direction would be greatly appreciated.

**Comment by lonvia** [comment]
This works quite similar to the node example. You need to create an explicit Reader which then exposes the header:

```
import osmium

reader = osmium.io.Reader(inputfile)
has_history = reader.header().has_multiple_object_versions

osmium.apply(reader, handler)
```

`has_multiple_object_versions` currently is the only attribute exported to python.

Leaving this ticket open as a reminder that the documentation for the osmium.io is not created properly, so that description of Readers and Header objects is missing.

**Comment by joto** [comment]
The online documentation is now fixed.

**Comment by batFINGER** [comment]
@lonvia thankyou, that's pretty much what I thought.. Are there plans to add `bounds` to the header info in the future?

**Comment by lonvia** [comment]
@batFINGER I've added that just yesterday, as it happens. `reader.header().box()` now returns an [osmium.osm.box](http://docs.osmcode.org/pyosmium/master/ref_osm.html#osmium.osm.Box) object with the bounds.
