### ISSUE TITLE
Should types implement a human readable representation

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/pyosmium#45]
At the moment the types exposed through Boost.Python have the default `__repr__` such as:

```python
<osmium.osm._osm.RelationMember object at 0x7f67a69e19a0>
```

which is not really helpful.

It would be great if types could expose a reasonable human readable representation e.g. the `RelationMember` type could format itself as

```python
<RelationMember ref=X, role=Y, type=Z>
```

maybe abbreviating the values if they're too long (`ref[:n]`).

**Comment by lonvia** [comment]
Turns out to be more tricky than expected. The [Python docs on repr()](https://docs.python.org/3/reference/datamodel.html#object.__repr__) state that the `__repr__` string should be an evaluable expression. Notwithstanding that this is not possible in practice because most of the classes are not constructable from Python, I still understand this to mean that a `__repr__` string should be a complete representation of the object. For nodes and relations that would mean including complete node and member lists. That can easily become a very long output. So my thinking is that if we do `__repr__`, we also need to provide a human-readable `__str__` version.

**Comment by lonvia** [comment]
So I've pushed something now where repr() yields something that looks like a constructor while str() gives you a shorter representation that is somewhat human readable. I was considering simply printing OPL for the str() version but I found it too concise for a user-readable string. So the version now is a little bit more verbose and also uses ellipses where the representation becomes too long.

**Comment by daniel-j-h** [comment]
Thanks for following up here so quickly! :)
