### ISSUE TITLE
How to create geometry from relation?

### ISSUE THREAD

**Issue by njanakiev** [osmcode/pyosmium#80]
I tried to get geometries from relations but I was getting `ArgumentError` for both `.create_linestring()` and `.create_multipolygon()`. I also tried both methods for each `r.member`element but with the same error. Both `area` and `way` geometries are working. Here is a snippet of my code:

```python
import osmium as osm
import shapely.wkb

wkb_factory = osm.geom.WKBFactory()

class OSMHandler(osm.SimpleHandler):
    def __init__(self):
        osm.SimpleHandler.__init__(self)
        self.amenities = []

    def relation(self, r):        
        if 'amenity' in r.tags:
            wkb = wkb_factory.create_linestring(r)
            multipolygon = shapely.wkb.loads(wkb, hex=True)
            lon, lat = line.centroid.x, line.centroid.y
            
            self.amenities.append([r.id, r.tags['amenity'], lon, lat])
                
handler = OSMHandler()
handler.apply_file('liechtenstein-latest.osm.pbf', locations=True)
```
    ArgumentError: Python argument types in
    WKBFactory.create_multipolygon(WKBFactory, Relation)
    did not match C++ signature:
    create_multipolygon(WKBFactory {lvalue} self, osmium::Area area)

Is there a proper way to get the geometry from a relation in pyosmium? Thank you in advance.

**Comment by wiktorn** [comment]
Relations as is do not have geometries. This is something that you can infer from tags. This is done for you in osmium so for relations that are multipolygons you will get an area and that what works for you.

As I understand - you would also like to have similar support for relations that represent line objects (such as routes). 

As far as I'm familiar with pyosmium and osmium, this is not implemented yet.

**Comment by njanakiev** [comment]
Thank you, @wiktorn. This means that the geometries of relations that are not tagged with `area=yes` are not accessible by pyosmium? 

Yes, I think it would be useful to be able to get the geometry from a relation as a multi polygon or multiline string. But I suppose that issue exists for osmium already?

**Comment by lonvia** [comment]
You can get multi-polygons for all non-broken relations tagged type=multipolygon or type=boundary. Use the area() callback instead of the relation() callback. Be aware though, that this also returns closed ways (i.e. it returns everything that represents an area in OSM)).

There is no way to return multi-linestrings from relation. This is covered as a feature request in #50 already.

**Comment by njanakiev** [comment]
Thank you for clarification, @lonvia

**Comment by aginpatrick** [comment]
@njanakiev Did you find a way to solve your problem ? I need the same to build a multi-linestring from relation

**Comment by keroe** [comment]
I wrote an [example](https://github.com/mvexel/python-osmium-examples/pull/4) which shows how you can get shapely polygons from relations. It is a bit clunky, but I had to do it this way, because I have a history file which is not compatible with the `area` callback. This can be adapted for linestrings from routes as well. Hope this helps.
