### ISSUE TITLE
find relation, way, node by id

### ISSUE THREAD

**Issue by camdeardorff** [osmcode/pyosmium#88]
This seems like something that would be easy to find but I'm having trouble finding any method to get a relation, way or node by their id or reference. Is this provided in the library?

**Comment by joto** [comment]
The way PyOsmium works you read an OSM file and get callbacks for each object in the file. PyOsmium doesn't doesn't keep the objects around (because this clogs up the memory with stuff you might not need). Ideally you can do whatever you need doing in these callbacks alone. If this is not enough, for instance if you need to look at members of a relation or so, you should store the data you need of the objects you need yourself. You know best exactly which data you will need, so this way only the needed data is stored. Often you can also read the input file twice (or more times), remembering IDs of objects you need from the first pass and then using the data in the second pass. This way, again, you can handle huge OSM files without using too much memory.

**Comment by camdeardorff** [comment]
Thank you, I was looking at my code and thought that having a couple of different handlers might be the wrong way to go about things but I understand the performance gains. Thanks again!
