### ISSUE TITLE
how to use get_replication_header for planet-latest

### ISSUE THREAD

**Issue by themmes** [osmcode/pyosmium#89]
Thank you so much for providing these handy bindings over the powerful osmium library, very useful so far.

I am trying to put a `'https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf'` through my custom handler and then continue from there with the `ReplicationServer`. However, "continue from there" is where I get stuck, I would like to retrieve the (latest) sequence id from this latest planet file.

So I explored the package, and found:
in `pyosmium/tools/pyosmium-up-to-date` there is the `compute_start_point()` function, which in my case (for a file) calls `get_replication_header`.

Problem is this will run through the entire file to find headers with (or from which can be derived) sequence ids. Even if (not sure if this is always true) the first header found is correct.

Two questions:
- Is there a better way to get the sequence id from the latest planet file?
- Shouldn't the `get_replication_header` be like a generator for which the user can choose whether it wants one or more headers to be parsed?

Thanks in advance for your time!

**Comment by themmes** [comment]
Indeed, `r.close()` for a local file works fine, it is only when using an URL that in my case it hangs. I probably will get the same error you are getting once it finishes reading.

Anyway, telling the reader to read nothing solves my problem of flooding memory and I guess I'll just leave the reader open. Thanks a lot for your quick response!

**Comment by joto** [comment]
While using a URL instead of a file is possible with Osmium, it is not well supported and any kind of error will not be detected properly. This is fine for one-off tasks, but if you want to script this, I recommend downloading the file first and, if that's successful, run Osmium on the file. And don't regularly download the planet file only to check its header, it might well download the whole file in the background without you noticing!
